version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: motioneye_app_1
      APP_PORT: 8765

  app:
    image: ccrisan/motioneye:master-amd64
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "8765:8765"
    volumes:
      - ${APP_DATA_DIR}/motioneye/config:/config
    container_name: motioneye_app_1
